name: Gerar APK Android

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar SDK necessário
        run: |
          sdkmanager "platforms;android-35" "build-tools;35.0.0" "platform-tools"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.11.1

      - name: Gerar APK debug
        run: gradle assembleDebug

      - name: Enviar APK como artifact
        uses: actions/upload-artifact@v4
        with:
          name: SorteadorDeTimes-APK
          path: app/build/outputs/apk/debug/*.apk
